[black]
include = '\.pyi?$'
exclude = '/(?:build|dist|venv|\.mypy_cache|\.pytest_cache|__pycache__)/'
docstring-style = "google"

[isort]
profile = "black"
force_sort_within_sections = true
force_single_line = true
lines_after_imports = 2

[flake8]
max-line-length = 120
ignore = "E501, W503"
exclude = ".tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules"

[pycodestyle]
max-line-length = 120
exclude = ".tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules"

[mypy]
python_version = 3.9
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
strict_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
